### ISSUE TITLE
Where to place third party libs?

### ISSUE THREAD

**Issue by sashaafm** [remojansen/ts-vscode-boilerplate#33]
Hello @remojansen I've started using (and learning) JS and TypeScript for a project and right now I've got a third party lib, which is CodeMirror, and I've like to know what's the proper way to add this lib to a project built with this template? 

I've created a `third_party` folder inside the root dir of the project/template and I've added the `@types` stuff in the `node_modules` using ` npm install --save @types/codemirror`. CodeMirror seems to be imported correctly in every class and interface (in the `entities` and `interfaces` dirs, respectively). I'm only getting an error in the `main.ts` file, which does not seem to be able to import CodeMirror correctly.

I've opened a [StackOverflow question](http://stackoverflow.com/questions/43238225/cannot-import-third-party-lib-codemirror-in-main-ts-but-works-everywhere-else) about this, if you mind to take a look. 

Thanks and thanks for the template, it was easy to setup and understand!

**Comment by remojansen** [comment]
You installed the type definitions:

> npm install --save-dev @types/codemirror

And that is correct (you should use `--save-dev`) but why you didn't install the library itself the same way?

> npm install --save codemirror

The library seems to be [available on npm](https://www.npmjs.com/package/codemirror).

If you don't understand the npm check out https://docs.npmjs.com/

I think the error you are getting is because TS looks for the files in the `node_modules` folder. You shouldn't need a custom `third_party` folder. All third party libraries should be installed via npm.

Check [this](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) and [this](https://www.typescriptlang.org/docs/handbook/module-resolution.html) out to learn about how typescript handles this.

Hope it helps!

**Comment by remojansen** [comment]
Can this issue be closed?

**Comment by sashaafm** [comment]
Hey @remojansen yes this explained and solved my issue. Thanks a lot!
