### ISSUE TITLE
Great work !! a small issue with jquery

### ISSUE THREAD

**Issue by IcodeNet** [remojansen/ts-vscode-boilerplate#4]
Hi @remojansen 
thanks for sharing this.
I have everything working pretty fast but I get in main.ts  and error 

cannot find module 'jquery'

 any ideas?

thanks in advance

**Comment by remojansen** [comment]
There has been an update of typings and I need to fix it... I haven't try this but you need to upgrade and create a new typings.json file:
```
$ npm install -g typings
$ rm typings.json
$ typings install --save --global dt~chai 
$ typings install --save --global dt~mocha
$ typings install --save --global dt~jquery
```

Then in the gulpfile there are a few reference to `"typings/main.d.ts/"` you need to change it to `"typings/index.d.ts/"`.

Sorry but I wont be able to update this template for a while because I have a lot of work on another open source project :(

Hope it helps.

**Comment by remojansen** [comment]
I have upgraded this to TS 2.0 added CI and enabled [greenkeper](https://greenkeeper.io/) so the example is always up to date 🚀
